Add Npc Stats dumper
deathbeam/osrs-data pull request #3
Opened 2019-04-10 19:33 UTC by TheStonedTurtle

Scraps the wiki for the below stats, if they exist, for all attackable npcs in the cache. Should handle variants as well

The dumped file will be written to `runelite/runelite-client/src/main/resources/npc_stats.json`

### Dumped stats
* hitpoints
* combat level
* slayer level
* attack level
* strength level
* defence level
* range level
* magic level
* stab bonus
* slash bonus
* crush bonus
* range bonus
* magic bonus
* stab defence bonus
* slash defence bonus
* crush defence bonus
* range defence bonus
* magic defence bonus
* bonus attack
* bonus strength
* bonus range strength
* bonus magic damage
* poison immune
* venom immune

2019-04-10 20:13 UTC, deathbeam requested changes

2019-04-10 20:13 UTC, deathbeam commented on src/main/java/net/runelite/data/dump/wiki/NpcStatsDumper.java
> +		final Set<Integer> npcIds = getAttackableNpcIds(npcManager);
use parallelStream like other dumpers do

2019-04-10 20:13 UTC, deathbeam commented on src/main/java/net/runelite/data/dump/wiki/NpcStatsDumper.java
> +		log.info("Dumping {} npc stats...this may take a while", npcIds.size());
this may take a while... is not necessary, just use exactly same format as other dumpers do

2019-04-10 20:13 UTC, deathbeam commented on src/main/java/net/runelite/data/dump/wiki/NpcStatsDumper.java
> +					continue;
this is not necessary

2019-04-10 20:13 UTC, deathbeam commented on src/main/java/net/runelite/data/dump/wiki/NpcStatsDumper.java
> +		log.info("Missed {} npcs", missed.size());
not necessary

2019-04-11 01:33 UTC, TheStonedTurtle commented
The PR has been updated to use parallel streams as well as fix a few other issues.

The first two commits are fixing "issues" that exist in the client that i ran into. The last commit is a work around for having the wiki having comments in the `Integer.parseInt()`, i wasn't sure if updating the main `getInt()` was a good idea so i localized the call for just this dump.

TL;DR needs a full review again :)

2019-04-11 07:09 UTC, deathbeam requested changes

2019-04-11 07:09 UTC, deathbeam commented on src/main/java/net/runelite/data/dump/MediaWikiTemplate.java
> +		final Pattern exactNameTest = Pattern.compile(name.toLowerCase() + "\\s*\\|");
you can just make the pattern case-insensitive. Also, if you want to match | also match {{ at start

2019-04-12 14:11 UTC, TheStonedTurtle commented
Okay i think this is ready again

2019-07-12 10:42 UTC, merged